# Generated by Django 5.2.12 on 2026-04-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_booking_user_alter_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
